import * as XLSX from "xlsx";
import { db, newId } from "../db";
import type { Company, Customer, Expense, ImportLog, Invoice, InvoiceItem, ServiceTemplate } from "../types";
import { addDays } from "./date";
import { allocateCustomerNumber } from "./customerNumbers";

type Row = unknown[];
type InvoiceRow = { invoiceNumber: string; name: string; street: string; postalCode: string; city: string; invoiceDate: string; photos: number; baseCents: number; extraPhotos: number; extraAmountCents: number; boxCents: number; shippingCents: number; discountCents: number; voucherCents: number; prepaidCents: number; paymentMethod: string; totalCents: number; paid: boolean; description: string; sourceSheet: string };
export type ExpenseRow = { date: string; supplier: string; description: string; category: string; totalCents: number; paymentMethod: string; receiptNumber: string; sourceSheet: string; costType?: "standard" | "travel"; tripPurpose?: string; startLocation?: string; destination?: string; kilometers?: number; kilometerRateCents?: number; parkingCents?: number; tollCents?: number };
export interface ExcelPreview { sourceName: string; fingerprint: string; sheets: string[]; years: number[]; structureVariant: string; rows: InvoiceRow[]; expenses: ExpenseRow[]; templates: string[]; warnings: string[]; errors: string[]; duplicateNumbers: string[]; possibleCustomerDuplicates: string[]; missingRequiredFields: number; unassignedRecords: number; }

const text = (v: unknown) => String(v ?? "").trim();
const key = (v: unknown) => text(v).toLocaleLowerCase("de").normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-z0-9]/g, "");
const number = (v: unknown) => { if (typeof v === "number") return Number.isFinite(v) ? v : 0; const s = text(v).replace(/\s|€/g, ""); if (!s) return 0; const normalized = s.includes(",") ? s.replace(/\./g, "").replace(",", ".") : s; const parsed = Number(normalized); return Number.isFinite(parsed) ? parsed : 0; };
const cents = (v: unknown) => Math.round(number(v) * 100);
const isoDate = (v: unknown) => { if (v instanceof Date && !Number.isNaN(v.getTime())) return v.toISOString().slice(0, 10); if (typeof v === "number" && v > 1) { const parsed = XLSX.SSF.parse_date_code(v); if (parsed) return `${parsed.y}-${String(parsed.m).padStart(2, "0")}-${String(parsed.d).padStart(2, "0")}`; } const s = text(v); const match = s.match(/^(\d{1,2})[./-](\d{1,2})[./-](\d{2,4})$/); if (match) return `${match[3]!.length === 2 ? "20" + match[3] : match[3]}-${match[2]!.padStart(2, "0")}-${match[1]!.padStart(2, "0")}`; return /^\d{4}-\d{2}-\d{2}/.test(s) ? s.slice(0, 10) : ""; };
const hashFile = async (file: File) => Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256", await file.arrayBuffer()))).map((b) => b.toString(16).padStart(2, "0")).join("");
const findHeader = (rows: Row[], pattern: RegExp) => rows.findIndex((row) => row.some((v) => pattern.test(key(v))));
const column = (headers: Row, ...names: RegExp[]) => headers.findIndex((v) => names.some((name) => name.test(key(v))));

interface Adapter { name: string; matches(headers: Row): boolean; parse(rows: Row[], sheet: string): InvoiceRow[]; }
const makeAdapter = (name: string, match: (h: Row) => boolean): Adapter => ({ name, matches: match, parse(rows, sourceSheet) {
  const hi = findHeader(rows, /rechnungs?(nr|nummer)/); if (hi < 0) return []; const h = rows[hi]!;
  const ix = { nr: column(h, /rechnungs?(nr|nummer)/), name: column(h, /^name$/), street: column(h, /strasse/), postal: column(h, /^plz/), city: column(h, /^ort$/), date: column(h, /^datum$/), photos: column(h, /bilder$/, /bearbeitetefotos/), base: column(h, /grundbetrag/, /gundbetrag/), extra: column(h, /zusatzl.*bilder$/, /zusatzlichbearbeitete/), extraAmount: column(h, /bilderbetrag/), box: column(h, /fotobox/), shipping: column(h, /versand/), discount: column(h, /rabatt/), voucher: column(h, /gutscheinabzug/), prepaid: column(h, /bereitsgezahlt/), method: column(h, /zahlungsart/, /unbar/), total: column(h, /rechnungsbetrag/, /gesamtbetrag/), paid: column(h, /^bezahlt$/), description: column(h, /rechnungstext/, /rechntext/) };
  return rows.slice(hi + 1).flatMap((r) => { const rawNr = text(r[ix.nr]); const invoiceNumber = /^\d+$/.test(rawNr) ? rawNr.padStart(5, "0") : ""; const name = text(r[ix.name]); const totalCents = cents(r[ix.total]); if (!invoiceNumber || !name || !totalCents) return []; return [{ invoiceNumber, name, street: text(r[ix.street]), postalCode: text(r[ix.postal]), city: text(r[ix.city]), invoiceDate: isoDate(r[ix.date]), photos: number(r[ix.photos]), baseCents: cents(r[ix.base]), extraPhotos: number(r[ix.extra]), extraAmountCents: cents(r[ix.extraAmount]), boxCents: cents(r[ix.box]), shippingCents: cents(r[ix.shipping]), discountCents: cents(r[ix.discount]), voucherCents: cents(r[ix.voucher]), prepaidCents: cents(r[ix.prepaid]), paymentMethod: text(r[ix.method]), totalCents, paid: /^(ja|yes|true|1)$/i.test(text(r[ix.paid])), description: text(r[ix.description]), sourceSheet }]; });
} });
const adapters = [
  makeAdapter("Legacy 2016–2017", (h) => !h.some((v) => /shootingart/.test(key(v)))),
  makeAdapter("Shooting-Tabelle 2018–2022", (h) => h.some((v) => /shootingart/.test(key(v))) && !h.some((v) => /gutscheinabzug/.test(key(v)))),
  makeAdapter("Gutschein/Teilzahlung 2023–2025", (h) => h.some((v) => /gutscheinabzug|bereitsgezahlt/.test(key(v))))
];

function parseTemplates(rows: Row[]) { const hi = findHeader(rows, /rechntext|rechnungstext/); if (hi < 0) return []; const h = rows[hi]!; const ci = column(h, /rechntext/, /rechnungstext/); return [...new Set(rows.slice(hi + 1).map((r) => text(r[ci])).filter((v) => v.length >= 10))]; }
function parseExpenses(rows: Row[], sourceSheet: string): ExpenseRow[] { const hi = rows.findIndex((r) => r.some((v) => /^kategorie$/.test(key(v))) && r.some((v) => /^preis|betrag/.test(key(v)))); if (hi < 0) return []; const h = rows[hi]!; const cat = column(h, /^kategorie$/), desc = column(h, /bemerkung/, /beschreibung/), date = column(h, /^datum$/), amount = column(h, /^preis/, /betrag/), supplier = column(h, /lieferant/), method = column(h, /zahlungsart/), receipt = column(h, /beleg/); return rows.slice(hi + 1).flatMap((r) => { const d = isoDate(r[date]), totalCents = cents(r[amount]); if (!d || totalCents <= 0) return []; return [{ date: d, supplier: text(r[supplier]), description: text(r[desc]), category: text(r[cat]) || "Importiert / nicht zugeordnet", totalCents, paymentMethod: text(r[method]), receiptNumber: text(r[receipt]), sourceSheet }]; }); }
function parseTravelExpenses(rows: Row[], sourceSheet: string): ExpenseRow[] { const hi = rows.findIndex((r) => r.some((v) => /^datum$/.test(key(v))) && r.some((v) => /fahrtkosten|gesamtbetrag|kosten|betrag/.test(key(v)))); if (hi < 0) return []; const h = rows[hi]!; const date = column(h, /^datum$/), purpose = column(h, /anlass/, /zweck/, /beschreibung/), start = column(h, /startort/, /^von$/), destination = column(h, /zielort/, /^nach$/), km = column(h, /kilometer/, /^km$/), rate = column(h, /kilometerpreis/, /pauschale/), total = column(h, /fahrtkosten/, /gesamtbetrag/, /^betrag$/, /^kosten$/), parking = column(h, /parkkosten/), toll = column(h, /maut/); return rows.slice(hi + 1).flatMap((r) => { const d = isoDate(r[date]), totalCents = cents(r[total]); if (!d || totalCents <= 0) return []; return [{ date: d, supplier: "Fahrtkosten", description: text(r[purpose]) || "Fahrtkosten", category: "Fahrtkosten", totalCents, paymentMethod: "", receiptNumber: "", sourceSheet, costType: "travel", tripPurpose: text(r[purpose]), startLocation: text(r[start]), destination: text(r[destination]), kilometers: number(r[km]) || undefined, kilometerRateCents: rate >= 0 ? cents(r[rate]) || undefined : undefined, parkingCents: cents(r[parking]) || undefined, tollCents: cents(r[toll]) || undefined }]; }); }

export async function previewExcel(file: File): Promise<ExcelPreview> {
  const buffer = await file.arrayBuffer(); const wb = XLSX.read(buffer, { type: "array", cellDates: true, dense: true, sheetRows: 20_000 }); const rows: InvoiceRow[] = [], expenses: ExpenseRow[] = []; let templates: string[] = []; const used = new Set<string>();
  for (const sheetName of wb.SheetNames) { const sheet = wb.Sheets[sheetName]; if (!sheet) continue; const matrix = XLSX.utils.sheet_to_json<Row>(sheet, { header: 1, defval: "", raw: true }); if (/kunden/i.test(sheetName)) { const hi = findHeader(matrix, /rechnungs?(nr|nummer)/); if (hi >= 0) { const adapter = adapters.find((a) => a.matches(matrix[hi]!)); if (adapter) { rows.push(...adapter.parse(matrix, sheetName)); used.add(adapter.name); } } templates.push(...parseTemplates(matrix)); } if (/ausgab|kosten|fahrt|kilometer|reise|abo|einkauf|beleg|gewinn|verlust|jahresubersicht/i.test(key(sheetName))) { const standard = parseExpenses(matrix, sheetName); expenses.push(...(standard.length ? standard : parseTravelExpenses(matrix, sheetName))); } }
  templates = [...new Set(templates.map((v) => v.trim()))]; const counts = new Map<string, number>(); rows.forEach((r) => counts.set(r.invoiceNumber, (counts.get(r.invoiceNumber) || 0) + 1)); const duplicateNumbers = [...counts].filter(([, n]) => n > 1).map(([n]) => n); const customerKeys = new Map<string, number>(); rows.forEach((r) => { const k = key(`${r.name}|${r.street}|${r.postalCode}|${r.city}`); customerKeys.set(k, (customerKeys.get(k) || 0) + 1); }); const possibleCustomerDuplicates = [...customerKeys].filter(([, n]) => n > 1).map(([k]) => k); const missingRequiredFields = rows.filter((r) => !r.invoiceDate || !r.street || !r.postalCode || !r.city).length; const warnings: string[] = []; if (missingRequiredFields) warnings.push(`${missingRequiredFields} Rechnungen haben unvollständige Pflichtdaten.`); if (duplicateNumbers.length) warnings.push(`Doppelte Rechnungsnummern in der Datei: ${duplicateNumbers.join(", ")}`); if (expenses.some((e) => !e.supplier)) warnings.push("Bei Ausgaben fehlen Lieferantenangaben; diese werden transparent als nicht aus Excel ersichtlich markiert."); const years = [...new Set([...rows.map((r) => Number(r.invoiceDate.slice(0, 4))), ...expenses.map((e) => Number(e.date.slice(0, 4)))].filter(Number.isFinite))].sort(); return { sourceName: file.name, fingerprint: await hashFile(file), sheets: wb.SheetNames, years, structureVariant: [...used].join(" + ") || "Nicht erkannt", rows, expenses, templates, warnings, errors: rows.length ? [] : ["Keine importierbaren Rechnungen erkannt."], duplicateNumbers, possibleCustomerDuplicates, missingRequiredFields, unassignedRecords: expenses.filter((e) => e.category === "Importiert / nicht zugeordnet").length };
}

const customerKey = (r: InvoiceRow) => key(`${r.name}|${r.street}|${r.postalCode}|${r.city}`);
function makeItems(row: InvoiceRow, warnings: string[]): InvoiceItem[] { const items: InvoiceItem[] = []; const push = (description: string, amount: number) => { if (amount) items.push({ id: newId("item"), description, quantityMilli: 1000, unit: "Pauschale", unitPriceCents: amount, totalCents: amount, sortOrder: items.length }); }; push(row.description || `Fotoshooting${row.photos ? ` inkl. ${row.photos} bearbeitete Bilder` : ""}`, row.baseCents); push(`${row.extraPhotos || "Zusätzliche"} bearbeitete Bilder`, row.extraAmountCents); push("Fotobox", row.boxCents); push("Verpackung und Versand", row.shippingCents); push("Rabatt", -row.discountCents); push("Gutscheinabzug", -row.voucherCents); const sum = items.reduce((s, i) => s + i.totalCents, 0); if (sum !== row.totalCents) { push("Aus Excel übernommener Differenzbetrag", row.totalCents - sum); warnings.push(`Rechnung ${row.invoiceNumber}: Positionswerte weichen um ${((row.totalCents - sum) / 100).toFixed(2)} EUR vom Rechnungsbetrag ab.`); } return items; }

export async function importExcel(preview: ExcelPreview, company: Company): Promise<ImportLog> {
  if (preview.errors.length || preview.duplicateNumbers.length) throw new Error("Importvorschau enthält blockierende Fehler."); if (await db.importLogs.where("sourceFingerprint").equals(preview.fingerprint).first()) throw new Error("Diese Datei wurde bereits vollständig importiert."); let imported = 0, skipped = 0, expensesImported = 0; const warnings = [...preview.warnings];
  await db.transaction("rw", [db.customers, db.invoices, db.payments, db.expenses, db.importLogs, db.serviceTemplates, db.settings], async () => {
    const customerCache = new Map<string, Customer>(); for (const c of await db.customers.toArray()) customerCache.set(key(`${[c.firstName, c.lastName].filter(Boolean).join(" ") || c.company}|${c.street}|${c.postalCode}|${c.city}`), c);
    for (const row of preview.rows) { if (await db.invoices.where("invoiceNumber").equals(row.invoiceNumber).first()) { skipped++; continue; } let customer = customerCache.get(customerKey(row)); if (!customer) { const parts = row.name.split(/\s+/); const now = new Date().toISOString(); customer = { id: newId("customer"), customerNumber: await allocateCustomerNumber(), firstName: parts.shift() || "", lastName: parts.join(" ") || "–", street: row.street, postalCode: row.postalCode, city: row.city, country: "Deutschland", archived: false, createdAt: now, updatedAt: now, importFingerprint: `${preview.fingerprint}:customer:${customerKey(row)}` }; await db.customers.add(customer); customerCache.set(customerKey(row), customer); }
      const date = row.invoiceDate || `${preview.years[0] || new Date().getFullYear()}-01-01`; const items = makeItems(row, warnings); const id = newId("invoice"); const { confirmedAt: _a, updatedAt: _b, ...companySnapshot } = company; void _a; void _b; const invoice: Invoice = { id, draftNumber: `IMPORT-${row.invoiceNumber}`, invoiceNumber: row.invoiceNumber, year: Number(date.slice(0, 4)), customerId: customer.id, customerSnapshot: { customerNumber: customer.customerNumber, displayName: row.name, street: row.street, postalCode: row.postalCode, city: row.city, country: "Deutschland" }, companySnapshot, invoiceDate: date, serviceDateFrom: date, items, totalCents: row.totalCents, paymentTermDays: company.paymentTermDays, dueDate: addDays(date, company.paymentTermDays), status: row.paid ? "paid" : row.prepaidCents > 0 ? "partially_paid" : "finalized", paidAt: row.paid ? date : undefined, paymentMethod: row.paymentMethod, introText: "", outroText: "", taxExemptionNote: company.taxExemptionNote, createdAt: date, updatedAt: date, finalizedAt: date, imported: true, importSource: `${preview.sourceName} / ${row.sourceSheet}`, importFingerprint: `${preview.fingerprint}:${row.sourceSheet}:${row.invoiceNumber}` }; await db.invoices.add(invoice); const paid = row.paid ? row.totalCents : Math.min(row.prepaidCents, row.totalCents); if (paid > 0) await db.payments.add({ id: newId("payment"), invoiceId: id, amountCents: paid, paidAt: date, method: row.paymentMethod || "Nicht aus Excel ersichtlich", note: "Zahlungsstatus aus Excel übernommen; konkretes Zahlungsdatum nicht vorhanden.", createdAt: new Date().toISOString() }); imported++; }
    for (const row of preview.expenses) { const fp = `${preview.fingerprint}:${row.sourceSheet}:${row.date}:${key(row.description)}:${row.totalCents}`; if (await db.expenses.where("importFingerprint").equals(fp).first()) continue; const now = new Date().toISOString(); const expense: Expense = { id: newId("expense"), receiptNumber: row.receiptNumber || undefined, date: row.date, paidAt: row.date, supplier: row.supplier || "Nicht aus Excel ersichtlich", description: row.description || row.category, category: row.category, totalCents: row.totalCents, businessSharePercent: 100, deductibleCents: row.totalCents, paymentMethod: row.paymentMethod || undefined, note: "Aus Excel importiert; Zahlungsdatum entspricht mangels separater Angabe dem Belegdatum.", cancelled: false, createdAt: now, updatedAt: now, imported: true, importSource: `${preview.sourceName} / ${row.sourceSheet}`, importFingerprint: fp, costType: row.costType || "standard", tripPurpose: row.tripPurpose, startLocation: row.startLocation, destination: row.destination, kilometers: row.kilometers, kilometerRateCents: row.kilometerRateCents, parkingCents: row.parkingCents, tollCents: row.tollCents }; await db.expenses.add(expense); expensesImported++; }
    for (const description of preview.templates) { const fp = `template:${key(description)}`; if (await db.serviceTemplates.where("sourceFingerprint").equals(fp).first()) continue; const now = new Date().toISOString(); const template: ServiceTemplate = { id: newId("template"), title: description.split(/[,.]/)[0]!.slice(0, 80), description, category: "Excel-Import 2025", sortOrder: await db.serviceTemplates.count(), archived: false, usageCount: 0, sourceFingerprint: fp, createdAt: now, updatedAt: now }; await db.serviceTemplates.add(template); }
    await db.importLogs.add({ id: newId("import"), createdAt: new Date().toISOString(), sourceName: preview.sourceName, sourceFingerprint: preview.fingerprint, years: preview.years, customersFound: new Set(preview.rows.map(customerKey)).size, invoicesFound: preview.rows.length, imported, skipped, warnings, structureVariant: preview.structureVariant, expensesFound: preview.expenses.length, expensesImported, templatesFound: preview.templates.length });
  }); return (await db.importLogs.where("sourceFingerprint").equals(preview.fingerprint).first())!;
}
