import { useState } from "react";
import { useLiveQuery } from "dexie-react-hooks";
import { Archive, Mail, Pencil, Phone, Plus, Search, X } from "lucide-react";
import { Link } from "react-router-dom";
import { audit, db, newId } from "../db";
import type { Customer } from "../types";
import { euro } from "../lib/money";
import { allocateCustomerNumber } from "../lib/customerNumbers";
import { useCloud } from "../cloud/context";
import { confirmCloudWrite } from "../cloud/writeFeedback";

const blank = (): Customer => ({ id: newId("customer"), firstName: "", lastName: "", street: "", postalCode: "", city: "", country: "Deutschland", archived: false, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() });

export function Customers() {
  const cloud = useCloud();
  const canWrite = !cloud.configured || cloud.membership?.role !== "read_only";
  const customers = useLiveQuery(() => db.customers.toArray(), [], []); const invoices = useLiveQuery(() => db.invoices.toArray(), [], []);
  const [query, setQuery] = useState(""); const [showArchived, setShowArchived] = useState(false); const [editing, setEditing] = useState<Customer>(); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [sort, setSort] = useState(() => localStorage.getItem("customerSort") || "name-asc");
  const metrics = new Map(customers.map((customer) => { const related = invoices.filter((invoice) => invoice.customerId === customer.id && invoice.status !== "cancelled"); return [customer.id, { count: related.length, turnover: related.reduce((sum, invoice) => sum + invoice.totalCents, 0), open: related.filter((invoice) => !["paid", "cancelled"].includes(invoice.status)).reduce((sum, invoice) => sum + invoice.totalCents, 0) }]; }));
  const filtered = customers.filter((customer) => (showArchived || !customer.archived) && `${customer.firstName} ${customer.lastName} ${customer.company} ${customer.city} ${customer.email} ${customer.customerNumber}`.toLocaleLowerCase("de").includes(query.toLocaleLowerCase("de"))).sort((a, b) => { const nameA = a.company || `${a.lastName} ${a.firstName}`, nameB = b.company || `${b.lastName} ${b.firstName}`; if (sort.startsWith("number")) return (a.customerNumber || "").localeCompare(b.customerNumber || "", "de", { numeric: true }) * (sort.endsWith("desc") ? -1 : 1); if (sort === "name-desc") return nameB.localeCompare(nameA, "de"); if (sort === "created-desc") return b.createdAt.localeCompare(a.createdAt); if (sort === "updated-desc") return b.updatedAt.localeCompare(a.updatedAt); const field = sort.startsWith("turnover") ? "turnover" : sort.startsWith("count") ? "count" : sort.startsWith("open") ? "open" : ""; if (field) return ((metrics.get(b.id)?.[field as "count"] || 0) - (metrics.get(a.id)?.[field as "count"] || 0)) * (sort.endsWith("asc") ? -1 : 1); return nameA.localeCompare(nameB, "de"); });
  const save = async () => {
    if (!editing || !canWrite) return; if ((!editing.firstName && !editing.company) || !editing.lastName || !editing.street || !editing.postalCode || !editing.city) return setError("Name und vollständige Anschrift sind erforderlich.");
    const before = await db.customers.get(editing.id); const next = { ...editing, customerNumber: editing.customerNumber || await allocateCustomerNumber(), updatedAt: new Date().toISOString() }; if (await db.customers.where("customerNumber").equals(next.customerNumber!).filter((item) => item.id !== next.id).first()) return setError("Diese Kundennummer ist bereits vergeben."); await db.customers.put(next); await audit(before ? "update" : "create", "customer", next.id, before, next); setMessage(await confirmCloudWrite(cloud, "Kunde")); setEditing(undefined); setError("");
  };
  const archive = async (customer: Customer) => { if (!canWrite) return; const next = { ...customer, archived: !customer.archived, updatedAt: new Date().toISOString() }; await db.customers.put(next); await audit(next.archived ? "archive" : "restore", "customer", customer.id, customer, next); setMessage(await confirmCloudWrite(cloud, next.archived ? "Kunde archiviert" : "Kunde aktiviert")); };
  return <>
    <header className="page-header"><div><span className="eyebrow">Stammdaten</span><h1>Kunden</h1><p>{customers.filter((customer) => !customer.archived).length} aktive Kunden · historische Kunden bleiben erhalten.{!canWrite && " · Nur-Lesen-Zugriff"}</p></div>{canWrite && <button className="primary" onClick={() => setEditing(blank())}><Plus /> Neuer Kunde</button>}</header>
    {message && <div className="notice success">{message}</div>}
    <section className="toolbar"><label className="search"><Search /><span className="sr-only">Suchen</span><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Name, Ort, E-Mail …" /></label><select aria-label="Kunden sortieren" value={sort} onChange={(e) => { setSort(e.target.value); localStorage.setItem("customerSort", e.target.value); }}><option value="name-asc">Name A–Z</option><option value="name-desc">Name Z–A</option><option value="number-asc">Kundennummer aufsteigend</option><option value="number-desc">Kundennummer absteigend</option><option value="created-desc">Zuletzt erstellt</option><option value="updated-desc">Zuletzt geändert</option><option value="turnover-desc">Höchster Umsatz</option><option value="turnover-asc">Niedrigster Umsatz</option><option value="count-desc">Meiste Rechnungen</option><option value="open-desc">Offene Forderungen</option></select><label className="check compact-check"><input type="checkbox" checked={showArchived} onChange={(e) => setShowArchived(e.target.checked)} /> Archivierte anzeigen</label><span>{filtered.length} Ergebnisse</span></section>
    <section className="customer-grid">{filtered.map((customer) => {
      const related = invoices.filter((invoice) => invoice.customerId === customer.id && invoice.status !== "cancelled"); const turnover = related.reduce((sum, invoice) => sum + invoice.totalCents, 0);
      return <article className="customer-card" key={customer.id}><div className="avatar">{(customer.firstName[0] || customer.company?.[0] || "K").toUpperCase()}</div><div className="customer-body"><div><h2>{[customer.firstName, customer.lastName].filter(Boolean).join(" ") || customer.company}</h2><p>{customer.company && `${customer.company} · `}{customer.street}, {customer.postalCode} {customer.city}</p></div><div className="contact-links">{customer.email && <a href={`mailto:${customer.email}`}><Mail />{customer.email}</a>}{customer.phone && <a href={`tel:${customer.phone}`}><Phone />{customer.phone}</a>}</div><div className="customer-stats"><span><small>Rechnungen</small><strong>{related.length}</strong></span><span><small>Umsatz</small><strong>{euro(turnover)}</strong></span></div>{canWrite && <div className="card-actions"><Link className="small-button" to={`/invoices/new?customer=${customer.id}`}><Plus /> Rechnung</Link><button className="icon-button" onClick={() => setEditing(customer)} aria-label="Kunde bearbeiten"><Pencil /></button><button className="icon-button" onClick={() => archive(customer)} aria-label={customer.archived ? "Kunde reaktivieren" : "Kunde archivieren"}><Archive /></button></div>}</div></article>;
    })}</section>{!filtered.length && <div className="empty panel">Keine passenden Kunden gefunden.</div>}
    {editing && <div className="modal-backdrop" role="presentation"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="customer-title"><div className="panel-title"><h2 id="customer-title">{customers.some((item) => item.id === editing.id) ? "Kunde bearbeiten" : "Kunde anlegen"}</h2><button className="icon-button" onClick={() => setEditing(undefined)} aria-label="Schließen"><X /></button></div><div className="form-grid">
      <label>Kundennummer<input value={editing.customerNumber || ""} onChange={(e) => setEditing({ ...editing, customerNumber: e.target.value })} /></label><label>Firma<input value={editing.company || ""} onChange={(e) => setEditing({ ...editing, company: e.target.value })} /></label><label>Vorname<input value={editing.firstName} onChange={(e) => setEditing({ ...editing, firstName: e.target.value })} /></label><label>Nachname*<input value={editing.lastName} onChange={(e) => setEditing({ ...editing, lastName: e.target.value })} /></label><label className="wide">Straße*<input value={editing.street} onChange={(e) => setEditing({ ...editing, street: e.target.value })} /></label><label>PLZ*<input inputMode="numeric" value={editing.postalCode} onChange={(e) => setEditing({ ...editing, postalCode: e.target.value })} /></label><label>Ort*<input value={editing.city} onChange={(e) => setEditing({ ...editing, city: e.target.value })} /></label><label>E-Mail<input type="email" value={editing.email || ""} onChange={(e) => setEditing({ ...editing, email: e.target.value })} /></label><label>Telefon<input type="tel" value={editing.phone || ""} onChange={(e) => setEditing({ ...editing, phone: e.target.value })} /></label><label className="wide">Notizen<textarea value={editing.notes || ""} onChange={(e) => setEditing({ ...editing, notes: e.target.value })} /></label>
    </div>{error && <p className="error">{error}</p>}<div className="modal-actions"><button className="secondary" onClick={() => setEditing(undefined)}>Abbrechen</button><button className="primary" onClick={save}>Speichern</button></div></section></div>}
  </>;
}
