import { useEffect, useState } from "react";
import { useLiveQuery } from "dexie-react-hooks";
import { Download, FileUp, Pause, Pencil, Play, Plus, Repeat, Search, X, XCircle } from "lucide-react";
import { audit, db, newId } from "../db";
import { formatDate, isoToday } from "../lib/date";
import { downloadBlob } from "../lib/pdf";
import { euro, parseEuroToCents } from "../lib/money";
import { EXPENSE_CATEGORIES, type Expense, type RecurringExpense } from "../types";
import { catchUpRecurringExpenses, intervalMonths } from "../lib/recurringExpenses";
import { useCloud } from "../cloud/context";

type ExpenseForm = Omit<Expense, "totalCents" | "deductibleCents"> & { total: string; attachment?: File };
const blank = (): ExpenseForm => ({ id: newId("expense"), date: isoToday(), paidAt: isoToday(), supplier: "", description: "", category: "Sonstiges", total: "", businessSharePercent: 100, cancelled: false, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() });
const toForm = (expense: Expense): ExpenseForm => ({ ...expense, total: (expense.totalCents / 100).toFixed(2).replace(".", ",") });
type RecurringForm = Omit<RecurringExpense, "amountCents"> & { amount: string };
const blankRecurring = (): RecurringForm => { const today = isoToday(); return { id: newId("recurring"), name: "", supplier: "", category: "Sonstiges", amount: "", startDate: today, interval: "monthly", intervalMonths: 1, nextDueDate: today, status: "active", creationMode: "confirm", businessSharePercent: 100, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }; };

export function Expenses() {
  const cloud = useCloud();
  const canWrite = !cloud.configured || cloud.membership?.role !== "read_only";
  const expenses = useLiveQuery(() => db.expenses.orderBy("paidAt").reverse().toArray(), [], []);
  const recurring = useLiveQuery(() => db.recurringExpenses.orderBy("nextDueDate").toArray(), [], []);
  const [year, setYear] = useState(String(new Date().getFullYear())); const [query, setQuery] = useState(""); const [editing, setEditing] = useState<ExpenseForm>(); const [editingRecurring, setEditingRecurring] = useState<RecurringForm>(); const [error, setError] = useState("");
  useEffect(() => { if (canWrite) void catchUpRecurringExpenses(); }, [canWrite]);
  const years = [...new Set([new Date().getFullYear(), ...expenses.map((expense) => Number(expense.paidAt.slice(0, 4)))])].sort((a, b) => b - a);
  const filtered = expenses.filter((expense) => (!year || expense.paidAt.startsWith(year)) && `${expense.supplier} ${expense.description} ${expense.category}`.toLocaleLowerCase("de").includes(query.toLocaleLowerCase("de")));
  const total = filtered.filter((expense) => !expense.cancelled).reduce((sum, expense) => sum + expense.deductibleCents, 0);
  const save = async () => {
    if (!editing || !canWrite) return; const totalCents = parseEuroToCents(editing.total); if (!editing.date || !editing.paidAt || !editing.supplier || !editing.description || totalCents <= 0) return setError("Datum, Zahlungsdatum, Lieferant, Beschreibung und positiver Betrag sind erforderlich.");
    if (editing.attachment && (editing.attachment.size > 15 * 1024 * 1024 || !["application/pdf", "application/xml", "text/xml", "image/jpeg", "image/png", "image/webp"].includes(editing.attachment.type))) return setError("Belege dürfen höchstens 15 MB groß und PDF, XML, JPEG, PNG oder WebP sein.");
    const before = await db.expenses.get(editing.id); const deductibleCents = Math.round(totalCents * editing.businessSharePercent / 100); let attachmentId = editing.attachmentId;
    await db.transaction("rw", db.expenses, db.attachments, async () => {
      if (editing.attachment) { attachmentId = newId("attachment"); await db.attachments.add({ id: attachmentId, ownerType: "expense", ownerId: editing.id, name: editing.attachment.name, mimeType: editing.attachment.type, size: editing.attachment.size, blob: editing.attachment, createdAt: new Date().toISOString() }); }
      const { total: _total, attachment: _attachment, ...base } = editing; void _total; void _attachment;
      await db.expenses.put({ ...base, totalCents, deductibleCents, attachmentId, updatedAt: new Date().toISOString() });
    });
    await audit(before ? "update" : "create", "expense", editing.id, before, { totalCents, deductibleCents }); setEditing(undefined); setError("");
  };
  const cancel = async (expense: Expense) => { if (!canWrite || !window.confirm("Ausgabe nachvollziehbar stornieren? Der Datensatz bleibt erhalten.")) return; await db.expenses.update(expense.id, { cancelled: true, updatedAt: new Date().toISOString() }); await audit("cancel", "expense", expense.id, expense, { ...expense, cancelled: true }); };
  const saveRecurring = async () => { if (!editingRecurring || !canWrite) return; const amountCents = parseEuroToCents(editingRecurring.amount); if (!editingRecurring.name || !editingRecurring.supplier || amountCents <= 0) return setError("Bezeichnung, Lieferant und positiver Betrag sind erforderlich."); const { amount: _amount, ...base } = editingRecurring; void _amount; await db.recurringExpenses.put({ ...base, amountCents, intervalMonths: intervalMonths(base.interval, base.intervalMonths), updatedAt: new Date().toISOString() }); await audit("save", "recurring-expense", base.id, undefined, base); setEditingRecurring(undefined); setError(""); await catchUpRecurringExpenses(); };
  const exportCsv = () => { const head = ["Datum", "Zahlungsdatum", "Lieferant", "Beschreibung", "Kategorie", "Bruttobetrag", "Betrieblicher Anteil", "Abziehbarer Betrag", "Status"]; const rows = filtered.map((expense) => [expense.date, expense.paidAt, expense.supplier, expense.description, expense.category, (expense.totalCents / 100).toFixed(2), `${expense.businessSharePercent}%`, (expense.deductibleCents / 100).toFixed(2), expense.cancelled ? "Storniert" : "Aktiv"]); const csv = [head, ...rows].map((row) => row.map((cell) => `"${String(cell).replace(/"/g, '""')}"`).join(";")).join("\r\n"); downloadBlob(new Blob([`\uFEFF${csv}`], { type: "text/csv;charset=utf-8" }), `Ausgaben_${year || "alle"}.csv`); };
  return <>
    <header className="page-header"><div><span className="eyebrow">Belege & Kosten</span><h1>Ausgaben</h1><p>Bruttobeträge, Fahrtkosten und wiederkehrende Kosten.{!canWrite && " · Nur-Lesen-Zugriff"}</p></div>{canWrite && <div className="actions"><button className="secondary" onClick={() => setEditingRecurring(blankRecurring())}><Repeat /> Wiederkehrende Ausgabe</button><button className="primary" onClick={() => setEditing(blank())}><Plus /> Neue Ausgabe</button></div>}</header>
    <section className="kpi-grid small"><article className="kpi featured"><span>Abziehbare Ausgaben {year}</span><strong>{euro(total)}</strong><small>{filtered.filter((item) => !item.cancelled).length} Buchungen</small></article></section>
    <section className="toolbar"><label className="search"><Search /><span className="sr-only">Suchen</span><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Lieferant, Beschreibung …" /></label><select value={year} onChange={(e) => setYear(e.target.value)}><option value="">Alle Jahre</option>{years.map((item) => <option key={item}>{item}</option>)}</select><button className="secondary" onClick={exportCsv}><Download /> CSV</button></section>
    <section className="panel table-panel"><div className="responsive-table"><table><thead><tr><th>Zahlung</th><th>Lieferant / Beschreibung</th><th>Kategorie</th><th>Anteil</th><th className="amount">Betrag</th><th></th></tr></thead><tbody>{filtered.map((expense) => <tr className={expense.cancelled ? "cancelled-row" : ""} key={expense.id}><td>{formatDate(expense.paidAt)}</td><td><strong>{expense.supplier}</strong><small>{expense.description}</small></td><td>{expense.category}</td><td>{expense.businessSharePercent}%</td><td className="amount"><strong>{euro(expense.deductibleCents)}</strong><small>von {euro(expense.totalCents)}</small></td><td>{canWrite && <div className="row-actions"><button aria-label="Bearbeiten" onClick={() => setEditing(toForm(expense))}><Pencil /></button>{!expense.cancelled && <button aria-label="Stornieren" onClick={() => cancel(expense)}><XCircle /></button>}</div>}</td></tr>)}</tbody></table></div>{!filtered.length && <div className="empty">Keine Ausgaben erfasst.</div>}</section>
    <section className="panel recurring-section"><div className="panel-title"><h2>Wiederkehrende Ausgaben</h2><span>{expenses.filter((item) => item.confirmationStatus === "pending" && !item.cancelled).length} zur Bestätigung</span></div>{recurring.length ? recurring.map((item) => <div className="log-row" key={item.id}><span><strong>{item.name} · {euro(item.amountCents)}</strong><small>{item.interval} · nächste Fälligkeit {formatDate(item.nextDueDate)} · {item.creationMode === "automatic" ? "automatisch" : "Bestätigung"}</small></span>{canWrite && <span><button className="icon-button" aria-label="Wiederkehrende Ausgabe bearbeiten" onClick={() => setEditingRecurring({ ...item, amount: (item.amountCents / 100).toFixed(2).replace(".", ",") })}><Pencil /></button><button className="icon-button" aria-label={item.status === "paused" ? "Fortsetzen" : "Pausieren"} onClick={() => db.recurringExpenses.update(item.id, { status: item.status === "paused" ? "active" : "paused", updatedAt: new Date().toISOString() })}>{item.status === "paused" ? <Play /> : <Pause />}</button></span>}</div>) : <p className="empty">Noch keine wiederkehrenden Ausgaben.</p>}</section>
    {editingRecurring && <div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true"><div className="panel-title"><h2>Wiederkehrende Ausgabe</h2><button className="icon-button" onClick={() => setEditingRecurring(undefined)} aria-label="Schließen"><X /></button></div><div className="form-grid"><label>Bezeichnung*<input value={editingRecurring.name} onChange={(e) => setEditingRecurring({ ...editingRecurring, name: e.target.value })} /></label><label>Lieferant*<input value={editingRecurring.supplier} onChange={(e) => setEditingRecurring({ ...editingRecurring, supplier: e.target.value })} /></label><label>Kategorie<select value={editingRecurring.category} onChange={(e) => setEditingRecurring({ ...editingRecurring, category: e.target.value })}>{EXPENSE_CATEGORIES.map((category) => <option key={category}>{category}</option>)}</select></label><label>Betrag*<input inputMode="decimal" value={editingRecurring.amount} onFocus={(e) => e.currentTarget.select()} onChange={(e) => setEditingRecurring({ ...editingRecurring, amount: e.target.value })} /></label><label>Startdatum<input type="date" value={editingRecurring.startDate} onChange={(e) => setEditingRecurring({ ...editingRecurring, startDate: e.target.value, nextDueDate: e.target.value })} /></label><label>Intervall<select value={editingRecurring.interval} onChange={(e) => setEditingRecurring({ ...editingRecurring, interval: e.target.value as RecurringExpense["interval"] })}><option value="monthly">Monatlich</option><option value="bimonthly">Alle zwei Monate</option><option value="quarterly">Vierteljährlich</option><option value="semiannual">Halbjährlich</option><option value="yearly">Jährlich</option></select></label><label>Erstellungsmodus<select value={editingRecurring.creationMode} onChange={(e) => setEditingRecurring({ ...editingRecurring, creationMode: e.target.value as RecurringExpense["creationMode"] })}><option value="confirm">Zur Bestätigung vormerken</option><option value="automatic">Automatisch eintragen</option></select></label><label>Enddatum<input type="date" value={editingRecurring.endDate || ""} onChange={(e) => setEditingRecurring({ ...editingRecurring, endDate: e.target.value || undefined })} /></label></div>{error && <p className="error">{error}</p>}<div className="modal-actions"><button className="secondary" onClick={() => setEditingRecurring(undefined)}>Abbrechen</button><button className="primary" onClick={saveRecurring}>Speichern</button></div></section></div>}
    {editing && <div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="expense-title"><div className="panel-title"><h2 id="expense-title">Ausgabe erfassen</h2><button className="icon-button" onClick={() => setEditing(undefined)} aria-label="Schließen"><X /></button></div><div className="form-grid">
      <label>Belegdatum*<input type="date" value={editing.date} onChange={(e) => setEditing({ ...editing, date: e.target.value })} /></label><label>Zahlungsdatum*<input type="date" value={editing.paidAt} onChange={(e) => setEditing({ ...editing, paidAt: e.target.value })} /></label><label>Lieferant*<input value={editing.supplier} onChange={(e) => setEditing({ ...editing, supplier: e.target.value })} /></label><label>Belegnummer<input value={editing.receiptNumber || ""} onChange={(e) => setEditing({ ...editing, receiptNumber: e.target.value })} /></label><label className="wide">Beschreibung*<input value={editing.description} onChange={(e) => setEditing({ ...editing, description: e.target.value })} /></label><label>Kategorie<select value={editing.category} onChange={(e) => setEditing({ ...editing, category: e.target.value })}>{EXPENSE_CATEGORIES.map((category) => <option key={category}>{category}</option>)}</select></label><label>Bruttobetrag*<input inputMode="decimal" value={editing.total} onChange={(e) => setEditing({ ...editing, total: e.target.value })} placeholder="0,00" /></label><label>Betrieblicher Anteil %<input type="number" min="0" max="100" value={editing.businessSharePercent} onChange={(e) => setEditing({ ...editing, businessSharePercent: Number(e.target.value) })} /></label><label>Zahlungsart<input value={editing.paymentMethod || ""} onChange={(e) => setEditing({ ...editing, paymentMethod: e.target.value })} /></label><label className="wide file-label"><FileUp /> Beleg (PDF, Bild oder XML)<input type="file" accept="application/pdf,image/jpeg,image/png,image/webp,application/xml,text/xml" onChange={(e) => setEditing({ ...editing, attachment: e.target.files?.[0] })} /><small>{editing.attachment?.name || (editing.attachmentId ? "Beleg bereits gespeichert" : "Maximal 15 MB")}</small></label><label className="wide">Notiz<textarea value={editing.note || ""} onChange={(e) => setEditing({ ...editing, note: e.target.value })} /></label>
    </div>{error && <p className="error">{error}</p>}<div className="modal-actions"><button className="secondary" onClick={() => setEditing(undefined)}>Abbrechen</button><button className="primary" onClick={save}>Speichern</button></div></section></div>}
  </>;
}
