import { useMemo, useState } from "react";
import { useLiveQuery } from "dexie-react-hooks";
import { FilePlus2, Filter, RotateCcw, Search, SlidersHorizontal, X } from "lucide-react";
import { Link } from "react-router-dom";
import { db } from "../db";
import { formatDate } from "../lib/date";
import { euro } from "../lib/money";
import type { Invoice, InvoiceStatus } from "../types";

const labels: Record<InvoiceStatus, string> = { draft: "Entwurf", finalized: "Finalisiert", sent: "Versendet", partially_paid: "Teilbezahlt", paid: "Bezahlt", overdue: "Überfällig", cancelled: "Storniert" };
const sortLabels: Record<string, string> = { "date-desc": "Neueste zuerst", "date-asc": "Älteste zuerst", "number-asc": "Rechnungsnummer aufsteigend", "number-desc": "Rechnungsnummer absteigend", "customer-asc": "Kunde A–Z", "customer-desc": "Kunde Z–A", "amount-asc": "Betrag aufsteigend", "amount-desc": "Betrag absteigend", status: "Status", "updated-desc": "Zuletzt geändert" };
const normalized = (value: unknown) => String(value ?? "").toLocaleLowerCase("de").normalize("NFD").replace(/[\u0300-\u036f]/g, "");
const parts = (value?: string) => (value || "").split(/(\d+)/).filter(Boolean).map((item) => /^\d+$/.test(item) ? Number(item) : item);
const logicalNumber = (a?: string, b?: string) => { const aa = parts(a), bb = parts(b); for (let index = 0; index < Math.max(aa.length, bb.length); index++) { if (aa[index] === bb[index]) continue; if (aa[index] === undefined) return -1; if (bb[index] === undefined) return 1; return aa[index]! < bb[index]! ? -1 : 1; } return 0; };

export function Invoices() {
  const invoices = useLiveQuery(() => db.invoices.toArray(), [], []); const customers = useLiveQuery(() => db.customers.toArray(), [], []); const years = useMemo(() => [...new Set(invoices.map((item) => item.year))].sort((a, b) => b - a), [invoices]);
  const [query, setQuery] = useState(""); const [year, setYear] = useState(""); const [status, setStatus] = useState(""); const [sort, setSort] = useState(() => localStorage.getItem("invoiceSort") || "date-desc"); const [showFilters, setShowFilters] = useState(false); const [showSort, setShowSort] = useState(false); const [min, setMin] = useState(""); const [max, setMax] = useState(""); const customerMap = new Map(customers.map((customer) => [customer.id, customer]));
  const haystack = (invoice: Invoice) => { const customer = customerMap.get(invoice.customerId); return normalized([invoice.invoiceNumber, invoice.draftNumber, customer?.customerNumber, customer?.firstName, customer?.lastName, customer?.company, customer?.city, customer?.email, invoice.items.map((item) => item.description).join(" "), (invoice.totalCents / 100).toFixed(2), invoice.invoiceDate, invoice.serviceDateFrom, labels[invoice.status], invoice.notes].join(" ")); };
  const filtered = invoices.filter((invoice) => (!year || invoice.year === Number(year)) && (!status || invoice.status === status) && (!query || haystack(invoice).includes(normalized(query))) && (!min || invoice.totalCents >= Number(min.replace(",", ".")) * 100) && (!max || invoice.totalCents <= Number(max.replace(",", ".")) * 100)).sort((a, b) => { const ca = customerMap.get(a.customerId), cb = customerMap.get(b.customerId); if (sort.startsWith("number")) return logicalNumber(a.invoiceNumber || a.draftNumber, b.invoiceNumber || b.draftNumber) * (sort.endsWith("desc") ? -1 : 1); if (sort.startsWith("date")) return a.invoiceDate.localeCompare(b.invoiceDate) * (sort.endsWith("desc") ? -1 : 1); if (sort.startsWith("customer")) return normalized(ca?.company || ca?.lastName).localeCompare(normalized(cb?.company || cb?.lastName), "de") * (sort.endsWith("desc") ? -1 : 1); if (sort.startsWith("amount")) return (a.totalCents - b.totalCents) * (sort.endsWith("desc") ? -1 : 1); if (sort === "status") return labels[a.status].localeCompare(labels[b.status], "de"); return b.updatedAt.localeCompare(a.updatedAt); });
  const reset = () => { setYear(""); setStatus(""); setMin(""); setMax(""); };
  return <><header className="page-header"><div><span className="eyebrow">Dokumente</span><h1>Rechnungen</h1><p>{filtered.length} von {invoices.length} Rechnungen · Sortiert: {sortLabels[sort]}</p></div><Link className="primary" to="/invoices/new"><FilePlus2 /> Neue Rechnung</Link></header>
    <section className="toolbar compact-invoice-toolbar"><label className="search"><Search /><span className="sr-only">Suchen</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Rechnung suchen …" /></label><button className="secondary" onClick={() => setShowFilters(true)}><Filter /> Filter</button><button className="secondary" onClick={() => setShowSort(true)}><SlidersHorizontal /> Sortieren</button><select aria-label="Jahr" value={year} onChange={(event) => setYear(event.target.value)}><option value="">Alle Jahre</option>{years.map((item) => <option key={item}>{item}</option>)}</select></section>
    <section className="panel table-panel"><div className="responsive-table"><table><thead><tr><th>Nummer</th><th>Kunde</th><th>Datum</th><th>Status</th><th className="amount">Betrag</th></tr></thead><tbody>{filtered.map((invoice) => <tr key={invoice.id}><td><Link to={`/invoices/${invoice.id}`}><strong>{invoice.invoiceNumber || invoice.draftNumber}</strong>{invoice.imported && <small>Importiert</small>}</Link></td><td>{invoice.customerSnapshot?.displayName || customerMap.get(invoice.customerId)?.lastName}</td><td>{formatDate(invoice.invoiceDate)}</td><td><span className={`status ${invoice.status}`}>{labels[invoice.status]}</span></td><td className="amount">{euro(invoice.totalCents)}</td></tr>)}</tbody></table></div>{!filtered.length && <div className="empty">Keine passenden Rechnungen gefunden.</div>}</section>
    {showSort && <div className="modal-backdrop"><section className="modal compact-modal" role="dialog" aria-modal="true"><div className="panel-title"><h2>Rechnungen sortieren</h2><button className="icon-button" onClick={() => setShowSort(false)} aria-label="Schließen"><X /></button></div><div className="sort-options">{Object.entries(sortLabels).map(([value, label]) => <button key={value} className={sort === value ? "primary" : "secondary"} onClick={() => { setSort(value); localStorage.setItem("invoiceSort", value); setShowSort(false); }}>{label}</button>)}</div></section></div>}
    {showFilters && <div className="modal-backdrop"><section className="modal compact-modal" role="dialog" aria-modal="true"><div className="panel-title"><h2>Rechnungen filtern</h2><button className="icon-button" onClick={() => setShowFilters(false)} aria-label="Schließen"><X /></button></div><div className="form-grid"><label>Status<select value={status} onChange={(event) => setStatus(event.target.value)}><option value="">Alle Status</option>{Object.entries(labels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label>Mindestbetrag<input inputMode="decimal" value={min} onChange={(event) => setMin(event.target.value)} /></label><label>Höchstbetrag<input inputMode="decimal" value={max} onChange={(event) => setMax(event.target.value)} /></label></div><div className="modal-actions"><button className="secondary" onClick={reset}><RotateCcw /> Zurücksetzen</button><button className="primary" onClick={() => setShowFilters(false)}>Übernehmen</button></div></section></div>}
  </>;
}
