import { useEffect, useState } from "react";
import { useLiveQuery } from "dexie-react-hooks";
import { useRegisterSW } from "virtual:pwa-register/react";
import { Check, CloudCog, DatabaseBackup, FileSpreadsheet, LockKeyhole, Moon, RefreshCw, RotateCcw, Save, Sun, Upload } from "lucide-react";
import { APP_VERSION, DB_SCHEMA_VERSION, audit, db, newId } from "../db";
import { exportBackup, restoreBackup } from "../lib/backup";
import { importExcel, previewExcel, type ExcelPreview } from "../lib/excelImport";
import type { Company, CustomerNumberConfig, ServiceTemplate } from "../types";
import { DEFAULT_CUSTOMER_NUMBER_CONFIG, getCustomerNumberConfig } from "../lib/customerNumbers";
const normalizedTemplate = (value: string) => value.toLocaleLowerCase("de").normalize("NFD").replace(/[\u0300-\u036f]/g, "");

export function Settings() {
  const storedCompany = useLiveQuery(() => db.company.get("company")); const importLogs = useLiveQuery(() => db.importLogs.orderBy("createdAt").reverse().toArray(), [], []); const lastBackup = useLiveQuery(() => db.settings.get("lastBackupAt")); const templates = useLiveQuery(() => db.serviceTemplates.orderBy("sortOrder").toArray(), [], []);
  const [company, setCompany] = useState<Company>(); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [password, setPassword] = useState(""); const [previews, setPreviews] = useState<ExcelPreview[]>([]); const [restoreFile, setRestoreFile] = useState<File>(); const [dark, setDark] = useState(localStorage.getItem("theme") === "dark"); const [customerConfig, setCustomerConfig] = useState<CustomerNumberConfig>(DEFAULT_CUSTOMER_NUMBER_CONFIG); const [templateQuery, setTemplateQuery] = useState("");
  useEffect(() => { if (storedCompany) setCompany(storedCompany); }, [storedCompany]);
  useEffect(() => { void getCustomerNumberConfig().then(setCustomerConfig); }, []);
  useEffect(() => { document.documentElement.dataset.theme = dark ? "dark" : "light"; localStorage.setItem("theme", dark ? "dark" : "light"); }, [dark]);
  const { needRefresh: [needRefresh], updateServiceWorker } = useRegisterSW({ onRegisteredSW: (_url, registration) => { if (registration) window.setInterval(() => registration.update(), 60 * 60 * 1000); } });
  const update = (key: keyof Company, value: string | number | boolean) => setCompany((current) => current ? { ...current, [key]: value } : current);
  const saveCompany = async () => { if (!company) return; if (!company.name || !company.owner || !company.street || !company.postalCode || !company.city || !company.taxNumber || !company.iban) return setError("Bitte füllen Sie alle Pflichtfelder aus."); if (company.smallBusiness && !company.taxExemptionNote.trim()) return setError("Der Kleinunternehmerhinweis darf nicht leer sein."); const before = await db.company.get("company"); const next = { ...company, updatedAt: new Date().toISOString() }; await db.company.put(next); await audit("update", "company", "company", before, next); setMessage("Unternehmensdaten gespeichert."); setError(""); };
  const selectExcel = async (files?: FileList | null) => { if (!files?.length) return; setError(""); setMessage(`${files.length} Arbeitsmappen werden ausschließlich lesend geprüft …`); try { const results: ExcelPreview[] = []; for (const file of Array.from(files)) results.push(await previewExcel(file)); setPreviews(results); setMessage(`${results.reduce((sum, item) => sum + item.rows.length, 0)} Rechnungen und ${results.reduce((sum, item) => sum + item.expenses.length, 0)} Ausgaben erkannt. Bitte Vorschau prüfen.`); } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)); setMessage(""); } };
  const runImport = async () => { if (!previews.length || !company) return; try { let imported = 0, skipped = 0, expenses = 0; for (const preview of previews) { try { const log = await importExcel(preview, company); imported += log.imported; skipped += log.skipped; expenses += log.expensesImported || 0; } catch (cause) { if (!(cause instanceof Error) || !cause.message.includes("bereits vollständig")) throw cause; skipped += preview.rows.length; } } setMessage(`${imported} Rechnungen und ${expenses} Ausgaben importiert, ${skipped} Rechnungen übersprungen.`); setPreviews([]); } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)); } };
  const saveCustomerConfig = async () => { await db.settings.put({ key: "customerNumberConfig", value: customerConfig }); setMessage("Kundennummernschema gespeichert."); };
  const addTemplate = async () => { const description = window.prompt("Text der neuen Beschreibungsvorlage"); if (!description?.trim()) return; const now = new Date().toISOString(); await db.serviceTemplates.add({ id: newId("template"), title: description.split(/[,.]/)[0]!.slice(0, 80), description: description.trim(), sortOrder: templates.length, archived: false, usageCount: 0, createdAt: now, updatedAt: now }); };
  const editTemplate = async (template: ServiceTemplate) => { const description = window.prompt("Beschreibungsvorlage bearbeiten", template.description); if (!description?.trim()) return; await db.serviceTemplates.update(template.id, { description: description.trim(), title: description.split(/[,.]/)[0]!.slice(0, 80), updatedAt: new Date().toISOString() }); };
  const deleteTemplate = async (template: ServiceTemplate) => { if (template.usageCount > 0) { window.alert("Diese Vorlage wurde bereits verwendet und wird deshalb archiviert, damit bestehende Rechnungen unverändert bleiben."); await db.serviceTemplates.update(template.id, { archived: true, archivedAt: new Date().toISOString(), updatedAt: new Date().toISOString() }); return; } if (!window.confirm("Möchtest du diese Beschreibungsvorlage wirklich löschen?")) return; await db.serviceTemplates.delete(template.id); };
  const restore = async () => { if (!restoreFile || !window.confirm("Die aktuelle lokale Datenbank wird vollständig durch das Backup ersetzt. Fortfahren?")) return; try { const result = await restoreBackup(restoreFile, password || undefined); setMessage(`Wiederhergestellt: ${result.customers} Kunden, ${result.invoices} Rechnungen, ${result.expenses} Ausgaben. App wird neu geladen.`); window.setTimeout(() => window.location.reload(), 1000); } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)); } };
  if (!company) return <p>Einstellungen werden geladen …</p>;
  return <>
    <header className="page-header"><div><span className="eyebrow">Konfiguration & Datensicherheit</span><h1>Einstellungen</h1><p>Unternehmensprofil, Import, Backups und App-Version.</p></div><button className="primary" onClick={saveCompany}><Save /> Speichern</button></header>
    {(message || error) && <div className={error ? "notice error" : "notice success"}>{error || message}</div>}
    <div className="settings-grid"><section className="panel settings-section"><h2>Unternehmensprofil</h2><p className="section-note">Diese Daten erscheinen auf neuen finalisierten Rechnungen. Historische Snapshots bleiben unverändert.</p><div className="form-grid">
      <label>Unternehmen*<input value={company.name} onChange={(e) => update("name", e.target.value)} /></label><label>Inhaberin*<input value={company.owner} onChange={(e) => update("owner", e.target.value)} /></label><label className="wide">Straße*<input value={company.street} onChange={(e) => update("street", e.target.value)} /></label><label>PLZ*<input inputMode="numeric" value={company.postalCode} onChange={(e) => update("postalCode", e.target.value)} /></label><label>Ort*<input value={company.city} onChange={(e) => update("city", e.target.value)} /></label><label>Telefon<input type="tel" value={company.phone} onChange={(e) => update("phone", e.target.value)} /></label><label>E-Mail<input type="email" value={company.email} onChange={(e) => update("email", e.target.value)} /></label><label>Weitere E-Mail<input type="email" value={company.secondaryEmail} onChange={(e) => update("secondaryEmail", e.target.value)} /></label><label>Website<input type="url" value={company.website} onChange={(e) => update("website", e.target.value)} /></label><label>Steuernummer*<input value={company.taxNumber} onChange={(e) => update("taxNumber", e.target.value)} /></label><label>Bank<input value={company.bankName} onChange={(e) => update("bankName", e.target.value)} /></label><label>BIC<input value={company.bic} onChange={(e) => update("bic", e.target.value)} /></label><label className="wide">IBAN*<input value={company.iban} onChange={(e) => update("iban", e.target.value)} /></label><label>Zahlungsziel<input type="number" min="0" value={company.paymentTermDays} onChange={(e) => update("paymentTermDays", Number(e.target.value))} /></label><label>Nummernschema<input value={company.invoiceNumberPattern} readOnly /><small>Aus Excel erkannt: fünfstellig fortlaufend</small></label><label className="wide">Kleinunternehmerhinweis*<textarea value={company.taxExemptionNote} onChange={(e) => update("taxExemptionNote", e.target.value)} /></label>
    </div></section>
    <div className="settings-side"><section className="panel settings-section"><div className="section-icon"><DatabaseBackup /></div><h2>Backup & Wiederherstellung</h2><p>Vollständiger, versionierter Export einschließlich PDFs, Belegen, Protokollen und Einstellungen.</p><label>Optionales Backup-Passwort<div className="input-icon"><LockKeyhole /><input type="password" value={password} onChange={(e) => setPassword(e.target.value)} placeholder="Leer = unverschlüsselt" /></div></label><button className="primary full" onClick={() => exportBackup(password || undefined)}><DatabaseBackup /> Vollständiges Backup</button><small>Letztes Backup: {lastBackup?.value ? new Intl.DateTimeFormat("de-DE", { dateStyle: "medium", timeStyle: "short" }).format(new Date(String(lastBackup.value))) : "noch keines"}</small><hr /><label className="file-button"><Upload /> Backup-Datei wählen<input type="file" accept="application/json" onChange={(e) => setRestoreFile(e.target.files?.[0])} /></label>{restoreFile && <button className="danger full" onClick={restore}><RotateCcw /> Backup wiederherstellen</button>}</section>
    <section className="panel settings-section"><div className="section-icon"><Moon /></div><h2>Darstellung</h2><button className="secondary full" onClick={() => setDark(!dark)}>{dark ? <Sun /> : <Moon />}{dark ? " Hellen Modus verwenden" : " Dunklen Modus verwenden"}</button></section></div>
    <section className="panel settings-section"><div className="section-icon"><FileSpreadsheet /></div><h2>Excel-Jahresimport</h2><p>Erkennt mehrere Jahresstrukturen. Hashes, Quellen-Fingerprints und Rechnungsnummern verhindern Doppelimporte.</p><label className="file-button"><FileSpreadsheet /> Excel-Dateien lesend prüfen<input type="file" accept=".xlsx,.xlsm" multiple onChange={(e) => selectExcel(e.target.files)} /></label>{previews.length > 0 && <div className="import-preview"><h3>Importvorschau</h3>{previews.map((preview) => <article key={preview.fingerprint}><h4>{preview.sourceName}</h4><dl className="summary"><div><dt>Jahr / Struktur</dt><dd>{preview.years.join(", ")} · {preview.structureVariant}</dd></div><div><dt>Rechnungen / Ausgaben / Zahlungen</dt><dd>{preview.rows.length} / {preview.expenses.length} / {preview.rows.filter((row) => row.paid || row.prepaidCents).length}</dd></div><div><dt>Vorlagen / Pflichtfelder / nicht zugeordnet</dt><dd>{preview.templates.length} / {preview.missingRequiredFields} / {preview.unassignedRecords}</dd></div></dl>{[...preview.warnings, ...preview.errors].map((warning) => <p className="error" key={warning}>{warning}</p>)}</article>)}<button className="primary" disabled={previews.some((item) => item.errors.length > 0 || item.duplicateNumbers.length > 0)} onClick={runImport}><Check /> Geprüfte Dateien importieren</button></div>}<h3>Importprotokolle</h3>{importLogs.length ? importLogs.map((log) => <div className="log-row" key={log.id}><span><strong>{log.sourceName}</strong><small>{log.structureVariant} · {new Intl.DateTimeFormat("de-DE").format(new Date(log.createdAt))}</small></span><span>{log.imported} Rechnungen · {log.expensesImported || 0} Ausgaben · {log.skipped} übersprungen</span></div>) : <p className="empty">Noch kein Importprotokoll.</p>}</section>
    <section className="panel settings-section"><h2>Automatische Kundennummern</h2><div className="form-grid"><label>Präfix<input value={customerConfig.prefix} onChange={(e) => setCustomerConfig({ ...customerConfig, prefix: e.target.value })} /></label><label>Startnummer<input type="number" value={customerConfig.startNumber} onChange={(e) => setCustomerConfig({ ...customerConfig, startNumber: Number(e.target.value) })} /></label><label>Stellen<input type="number" value={customerConfig.digits} onChange={(e) => setCustomerConfig({ ...customerConfig, digits: Number(e.target.value) })} /></label><label>Nächster Wert<input type="number" value={customerConfig.nextValue} onChange={(e) => setCustomerConfig({ ...customerConfig, nextValue: Number(e.target.value) })} /></label></div><button className="secondary" onClick={saveCustomerConfig}><Save /> Schema speichern</button></section>
    <section className="panel settings-section"><h2>Beschreibungsvorlagen</h2><div className="toolbar"><input value={templateQuery} onChange={(e) => setTemplateQuery(e.target.value)} placeholder="Vorlagen suchen" /><button className="primary" onClick={addTemplate}>Vorlage hinzufügen</button></div>{templates.filter((template) => normalizedTemplate(template.description).includes(normalizedTemplate(templateQuery))).map((template) => <div className="log-row" key={template.id}><span><strong>{template.title}</strong><small>{template.description} · {template.usageCount}× verwendet</small></span><span><button className="small-button" onClick={() => editTemplate(template)}>Bearbeiten</button><button className="small-button" onClick={() => db.serviceTemplates.update(template.id, { archived: !template.archived, archivedAt: template.archived ? undefined : new Date().toISOString() })}>{template.archived ? "Aktivieren" : "Archivieren"}</button><button className="danger" onClick={() => deleteTemplate(template)}>Löschen</button></span></div>)}</section>
    <section className="panel settings-section"><div className="section-icon"><CloudCog /></div><h2>App-Version & Updates</h2><dl className="summary"><div><dt>Version</dt><dd>{APP_VERSION}</dd></div><div><dt>Datenbankschema</dt><dd>{DB_SCHEMA_VERSION}</dd></div><div><dt>Update</dt><dd>{needRefresh ? "Neue Version bereit" : "Aktuell"}</dd></div></dl><button className="secondary full" onClick={() => window.location.reload()}><RefreshCw /> Nach Updates suchen</button>{needRefresh && <button className="primary full" onClick={() => updateServiceWorker(true)}><CloudCog /> Update installieren</button>}<p className="section-note">Updates ersetzen nur den App-Cache. IndexedDB-Nutzerdaten werden nicht gelöscht. Speichern Sie Entwürfe vor dem Aktualisieren.</p></section>
    <section className="panel settings-section legal"><h2>Rechtliche Einordnung</h2><p>Die App setzt technische Schutzmaßnahmen für unveränderliche Belege, Protokollierung und Exporte um. Sie ist weder „GoBD-zertifiziert“ noch eine Steuer- oder Rechtsberatung.</p><p>Kleinunternehmerrechnungen werden ohne Umsatzsteuerausweis erstellt. Die strukturierte E-Rechnung ist für eine spätere Version vorbereitet, aber in 0.1.0 nicht implementiert.</p></section></div>
  </>;
}
